# Generated by Django 3.1.3 on 2021-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_hide_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_filter',
            field=models.BooleanField(default=True),
        ),
    ]
