# Generated by Django 3.1.3 on 2021-03-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_category_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='hide_sub_category',
            field=models.BooleanField(default=False),
        ),
    ]
