# Generated by Django 3.1.3 on 2021-08-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_social_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(default='shawon', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile',
            field=models.CharField(default='01863714903', max_length=200),
            preserve_default=False,
        ),
    ]
