# Generated by Django 3.1.3 on 2021-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productslider',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='productslider',
            name='button_name',
        ),
        migrations.RemoveField(
            model_name='productslider',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productslider',
            name='show_button',
        ),
        migrations.RemoveField(
            model_name='productslider',
            name='show_slider',
        ),
        migrations.RemoveField(
            model_name='productslider',
            name='title',
        ),
        migrations.AddField(
            model_name='productslider',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
