# Generated by Django 3.1.3 on 2021-03-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210307_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
