# Generated by Django 3.1.3 on 2021-08-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210321_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogoandtitle',
            name='slider_image_height',
            field=models.PositiveIntegerField(default=580),
        ),
    ]
