# Generated by Django 3.1.3 on 2021-08-26 06:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sitelogoandtitle_slider_image_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='description',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='q1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.CharField(default='ans', max_length=250),
            preserve_default=False,
        ),
    ]
